{
 "title": "Controle de Energia Supermarket",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Consumo Total no Último Mês (kWh)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM(\"consumo mensal\") FROM (\nSELECT\n  $__timeGroupAlias(\"time\",1h),\n  (avg(valor)/1000) AS \"consumo mensal\"\nFROM (SELECT med_labsoft.\"time\",\n    med_labsoft.total AS valor\n   FROM med_labsoft\n  ORDER BY med_labsoft.\"time\"\n) as consumo_watts_ar_cond_labsoft\nWHERE\n  time >= date_trunc('month', now()) - interval '1 month' AND\n  time < date_trunc('month', now())\nGROUP BY 1\nORDER BY 1\n) AS C"
    }
   ]
  },
  {
   "title": "Custo da Energia no Último Mês ",
   "type": "singlestat",
   "description": "Valor estimado",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM(\"consumo mensal\")  * 0.42880 as Custo FROM (\nSELECT\n  $__timeGroupAlias(\"time\",1h),\n  (avg(consumo_total)/1000) AS \"consumo mensal\"\nFROM consumo_watts_labsoft\nWHERE\n  time >= date_trunc('month', now()) - interval '1 month' AND\n  time < date_trunc('month', now())\nGROUP BY 1\nORDER BY 1\n) AS C"
    }
   ]
  },
  {
   "title": "Variação do Consumo Total (kWh) ",
   "type": "heatmap",
   "description": "Dados do último Mês",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h,NULL),\n  avg(total) AS \"total\"\nFROM med_labsoft\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Refrigeração de Produtos",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM(\"consumo mensal\") FROM (\nSELECT\n  $__timeGroupAlias(\"time\",1h),\n  (avg(valor)/1000) AS \"consumo mensal\"\nFROM (SELECT med_labsoft.\"time\",\n    med_labsoft.ar_cond AS valor\n   FROM med_labsoft\n  ORDER BY med_labsoft.\"time\"\n) as consumo_watts_ar_cond_labsoft\nWHERE\n  time >= date_trunc('month', now()) - interval '1 month' AND\n  time < date_trunc('month', now())\nGROUP BY 1\nORDER BY 1\n) AS C"
    }
   ]
  },
  {
   "title": "Consumo Total (kWh) e Custo (R$)",
   "type": "graph",
   "gridPos": { "h": 18, "w": 19, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  avg(consumo_total)/1000 AS \"consumo_total\"\nFROM consumo_watts_labsoft\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  (avg(consumo_total)/1000)* 0.42880 AS \"custo\"\nFROM consumo_watts_labsoft\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ar condicionado",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM(\"consumo mensal\") FROM (\nSELECT\n  $__timeGroupAlias(\"time\",1h),\n  (avg(valor)/1000) AS \"consumo mensal\"\nFROM consumo_watts_bancadas_labsoft\nWHERE\n  time >= date_trunc('month', now()) - interval '1 month' AND\n  time < date_trunc('month', now())\nGROUP BY 1\nORDER BY 1\n) AS C"
    }
   ]
  },
  {
   "title": "Iluminação",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM(\"consumo mensal\") FROM (\nSELECT\n  $__timeGroupAlias(\"time\",1h),\n  (avg(valor)/1000) AS \"consumo mensal\"\nFROM (SELECT med_labsoft.\"time\",\n    med_labsoft.rede AS valor\n   FROM med_labsoft\n  ORDER BY med_labsoft.\"time\"\n) as consumo_watts_rede_labsoft\nWHERE\n  time >= date_trunc('month', now()) - interval '1 month' AND\n  time < date_trunc('month', now())\nGROUP BY 1\nORDER BY 1\n) AS C"
    }
   ]
  },
  {
   "title": "Computadores",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM(\"consumo mensal\") FROM (\nSELECT\n  $__timeGroupAlias(\"time\",1h),\n  (avg(valor)/1000) AS \"consumo mensal\"\nFROM consumo_watts_iluminacao_labsoft\nWHERE\n  time >= date_trunc('month', now()) - interval '1 month' AND\n  time < date_trunc('month', now())\nGROUP BY 1\nORDER BY 1\n) AS C"
    }
   ]
  },
  {
   "title": "Outros",
   "type": "singlestat",
   "description": "Balanças, Consultor de Preço, Fatiador de Frios e Carregador de Máquinas de Cartão",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM(\"consumo mensal\") FROM (\nSELECT\n  $__timeGroupAlias(\"time\",1h),\n  (avg(valor)/1000) AS \"consumo mensal\"\nFROM (SELECT med_labsoft.\"time\",\n    med_labsoft.servidor AS valor\n   FROM med_labsoft\n  ORDER BY med_labsoft.\"time\"\n) as consumo_watts_servidor_labsoft\nWHERE\n  time >= date_trunc('month', now()) - interval '1 month' AND\n  time < date_trunc('month', now())\nGROUP BY 1\nORDER BY 1\n) AS C"
    }
   ]
  }
 ]
}